List='num1','num2','num3','num4','num5'
num1=input("Please enter a value:")
print(f"First value is {num1}")
print("Entered first value:{}".format(type(num1)))
num2=int(input("Please enter a value:"))
print(f"Second value is {num2}")
print("Entered second value:{}".format(type(num2)))
num3=float(input("Please enter a value:"))
print(f"Third value is {num3}")
print("Entered third value:{}".format(type(num3)))
num4=str(input("Please enter a value:"))
print(f"Fourth value is {num4}")
print("Entered forth value:{}".format(type(num4)))
num5=bool(input("Please enter a value:"))
print(f"Fifth value is {num5}")
print("Entered fifth value:{}".format(type(num5)))
